class AppConstants {
  AppConstants._();
  // MVP branch and subject data for StudyVault
  // static const List<String> items = [
  //   'Delhi University',
  //   'Gurugram University',
  //   'Mumbai University',
  //   'Bangalore University',
  // ];
  static const List<String> semesters = [
    'Semester I',
    'Semester II',
    'Semester III',
    'Semester IV',
    'Semester V',
    'Semester VI',
    'Semester VII',
    'Semester VIII',
  ];
  static const Map<String, List<String>> mvpSubjectsByBranch = {
    'CSE': [
      'DSA',
      'DBMS',
      'Operating Systems',
      'Computer Networks',
      'Software Engineering',
      'Java',
      'Python',
      'AI',
      'Machine Learning',
    ],

    'IT': [
      'DSA',
      'DBMS',
      'Operating Systems',
      'Computer Networks',
      'Web Development',
      'Java',
      'Python',
    ],

    'ECE': [
      'Digital Electronics',
      'Signals & Systems',
      'Microprocessors',
      'Communication Systems',
      'Embedded Systems',
    ],

    'EEE': [
      'Electrical Machines',
      'Power Systems',
      'Control Systems',
      'Power Electronics',
    ],

    'EE': [
      'Electrical Machines',
      'Power Systems',
      'Control Systems',
      'Network Theory',
    ],

    'Mechanical': [
      'Thermodynamics',
      'Fluid Mechanics',
      'Machine Design',
      'Manufacturing Processes',
    ],

    'Civil': [
      'Surveying',
      'Structural Analysis',
      'Concrete Technology',
      'Geotechnical Engineering',
    ],

    'Chemical': [
      'Chemical Process Calculations',
      'Heat Transfer',
      'Mass Transfer',
      'Reaction Engineering',
    ],

    'AI & ML': [
      'Machine Learning',
      'Deep Learning',
      'Python',
      'Data Science',
      'Artificial Intelligence',
    ],

    'Data Science': [
      'Statistics',
      'Python',
      'Machine Learning',
      'Data Visualization',
      'Big Data',
    ],

    'Cyber Security': [
      'Network Security',
      'Cryptography',
      'Ethical Hacking',
      'Cyber Forensics',
    ],
  };

  static const List<String> branches = [
    'CSE',
    'IT',
    'ECE',
    'EEE',
    'EE',
    'Mechanical',
    'Civil',
    'Chemical',
    'AI & ML',
    'Data Science',
    'Cyber Security',
  ];
  static const List<String> colleges = [
    'Central Tribal University of Andhra Pradesh (CTU AP)',
    'Central University of Andhra Pradesh (CU Andhra Pradesh)',
    'Indian Maritime University (IMU)',
    'National Sanskrit University (NSKTU Tirupati)',
    'Acharya Nagarjuna University',
    'Acharya NG Ranga Agricultural University (ANGRAU)',
    'Adikavi Nannaya University (AKNU)',
    'Andhra University',
    'Damodaram Sanjivayya National Law University (DSNLU)',
    'Dhanamanjuri University',
    'Dr BRAmbedkar University Srikakulam',
    'Dr NTR University of Health Sciences',
    'Dr YSR Architecture and Fine Arts University (YSRAFU)',
    'Dravidian University',
    'Jawaharlal Nehru Technological University Anantapur (JNTUA)',
    'Jawaharlal Nehru Technological University Hyderabad (JNTUH)',
    'Jawaharlal Nehru Technological University Kakinada (JNTUK)',
    'Karnataka State Akkamahadevi Women University (KSAWU)',
    'Krishna University',
    'Rajiv Gandhi University of Knowledge Technologies (RGUKT)',
    'Sri Krishnadevaraya University (SK University)',
    'Sri Padmavati Mahila Visvavidyalayam (SPMVV)',
    'Sri Venkateswara Institute of Medical Sciences (SVIMS)',
    'Sri Venkateswara University (SVU Tirupati)',
    'Sri Venkateswara Vedic University (SVVU)',
    'Sri Venkateswara Veterinary University (SVVU)',
    'Vikrama Simhapuri University',
    'Yogi Vemana University (YVU)',
    'Gandhi Institute of Technology and Management',
    'K L University',
    'SRM University',
    'Vignan University',
    'Gitam University',
    'Maharishi University of Management and Technology',
    'Rayalaseema University',
    'Sri Sathya Sai University',
    'All India Institute of Medical Sciences Mangalagiri (AIIMS Mangalagiri)',
    'Central Institute of Fisheries Nautical and Engineering Training (CIFNET)',
    'Central Institute of Tool Design (CITD)',
    'Indian Culinary Institute (ICI)',
    'Indian Institute of Information Technology Design and Manufacturing Kurnool (IIITDM Kurnool)',
    'Indian Institute of Information Technology Sri City (IIIT Sri City)',
    'Indian Institute of Management Visakhapatnam (IIM Vizag)',
    'Indian Institute of Petroleum and Energy (IIPE)',
    'Indian Institute of Science Education and Research Tirupati (IISER Tirupati)',
    'Indian Institute of Technology Tirupati (IIT Tirupati)',
    'Indian Institute of Tourism and Travel Management Nellore (IITTM Nellore)',
    'National Institute of Design (NID)',
    'National Institute of Technology Andhra Pradesh (NIT Andhra Pradesh)',
    'School of Planning and Architecture Vijayawada (SPA Vijayawada)',
    'SPKM Indian Institute of Handloom Technology Venktagiri',
    'Himalayan University',
    'Rajiv Gandhi University (RGU)',
    'North Eastern Regional Institute of Science and Technology (NERIST)',
    'Arunachal Universuty of Studies',
    'Arunodaya University',
    'Indira Gandhi Technological and Medical Sciences University',
    'North East Frontier Technical University',
    'Venkateshwara Open University',
    'National Institute of Electronics and Information Technology (NIELIT)',
    'National Institute of Technology Arunachal Pradesh (NIT Arunachal Pradesh)',
    'Assam Agricultural University (AAU)',
    'Assam University (AU Silchar)',
    'Tezpur University (TEZU)',
    'Assam Rajiv Gandhi University of Cooperative Management (ARGUCOM)',
    'Assam Science and Technology University (ASTU)',
    'Assam Womens University (AWU)',
    'Bhattadev University',
    'Bodoland University',
    'Cotton University',
    'Dibrugarh University',
    'Gauhati University',
    'Krishna Kanta Handiqui State Open University (KKHSOU)',
    'Kumar Bhaskar Varma Sanskrit and Ancient Studies University (KBVSASUN)',
    'Madhabdev University',
    'National Law University and Judicial Academy Assam (NLUJA Assam)',
    'Sri Sri Aniruddhadeva Sports University (SASU)',
    'Srimanta Sankaradeva University of Health Sciences (SSUHS)',
    'Assam Don Bosco University (ADBU)',
    'Assam Down Town University',
    'Kaziranga University',
    'Mahapurusha Srimanta Sankaradeva Viswavidyalaya (MSSV)',
    'Royal Global University',
    'Army Institute of Nursing Guwahati (AIN Guwahati)',
    'Central Institute of Technology Kokrajhar (CIT Kokrajhar)',
    'Dr Bhubaneswar Borooah Cancer Institute (BBCI)',
    'Indian Institute of Handloom Technology Guwahati (IIHT Guwahati)',
    'Indian Institute of Information Technology Guwahati (IIIT Guwahati)',
    'Indian Institute of Technology Guwahati (IIT Guwahati)',
    'Indian Statistical Institute Tezpur (ISI Tezpur)',
    'National Institute of Pharmaceutical Education and Research Guwahati (NIPER Guwahati)',
    'National Institute of Technology Silchar (NIT Silchar)',
    'National Power Training Institute (NPTI)',
    'North Eastern Regional Institute of Water and Land Management (NERIWALM)',
    'Institute of Advanced Study in Science and Technology (IASST)',
    'Central University of South Bihar (CUSB)',
    'Dr Rajendra Prasad Central Agricultural University (RPCAU)',
    'Mahatma Gandhi Central University Bihar (MGCUB)',
    'Nalanda University',
    'Aryabhatta Knowledge University (AKU Bihar)',
    'Babasaheb Bhimrao Ambedkar Bihar University (BRABU)',
    'Bhupendra Narayan Mandal University (BNMU)',
    'Bihar Agricultural University (BAU)',
    'Bihar Animal Sciences University (BASU)',
    'Chanakya National Law University (CNLU)',
    'Jai Prakash University (JPU)',
    'Kameshwar Singh Darbhanga Sanskrit University (KSDSU)',
    'Lalit Narayan Mithila University (LNMU)',
    'Magadh University',
    'Maulana Mazharul Haque Arabic and Persian University (MMHAPU)',
    'Munger University',
    'Nalanda Open University',
    'Nava Nalanda Mahavihara (NNM)',
    'Patna University',
    'Tilka Manjhi Bhagalpur University (TMBU)',
    'Veer Kunwar Singh University (VKSU)',
    'Bihar School of Yoga (Bihar Yoga Bharti)',
    'Amity University',
    'K K University',
    'All India Institute of Medical Sciences Patna (AIIMS Patna)',
    'Indian Institute of Information Technology Bhagalpur (IIIT Bhagalpur)',
    'Indian Institute of Management Bodh Gaya (IIM Bodh Gaya)',
    'Indian Institute of Technology Patna (IIT Patna)',
    'Institute of Hotel Management Hajipur (IHM Hajipur)',
    'National Institute of Fashion Technology (NIFT)',
    'National Institute of Pharmaceutical Education and Research Hajipur (NIPER Hajipur)',
    'National Institute of Technology Patna (NIT Patna)',
    'Chandigarh University',
    'National Institute of Technical Teachers Training and Research Chandigarh (NITTTR Chandigarh)',
    'Guru Ghasidas University (GGU Bilaspur)',
    'Atal Bihari Vajpayee Bilaspur University (ABVV)',
    'Chhattisgarh Kamdhenu Vishwavidyalaya (CGKV)',
    'Chhattisgarh Swami Vivekanand Technical University (CSVTU)',
    'Durg University',
    'Hidayatullah National Law University (HNLU)',
    'Indira Gandhi Agricultural University (IGAU)',
    'Indira Kala Sangeet Vishwavidyalaya (IKSV)',
    'Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya (KTUJM)',
    'Pandit Ravishankar Shukla University (PRSU)',
    'Pandit Sundarlal Sharma University Chhattisgarh (PSSOU)',
    'Pt Deendayal Upadhyay Memorial Health Sciences and Ayush University of Chhattisgarh',
    'Sarguja University',
    'Shaheed Mahendra Karma Vishwavidyalaya (Bastar University)',
    'Dr C V Raman University',
    'ICFAI University',
    'ISBM University',
    'ITM University',
    'Kalinga University',
    'MATS University',
    'OP Jindal University',
    'All India Institute of Medical Sciences (AIIMS Bilaspur)',
    'All India Institute of Medical Sciences Raipur (AIIMS Raipur)',
    'Indian Institute of Handloom Technology Champa (IIHT Chhattisgarh)',
    'Indian Institute of Management Raipur (IIM Raipur)',
    'Indian Institute of Technology Bhilai (IIT Bhilai)',
    'National Institute of Technology Raipur (NIT Raipur)',
    'School of Archival Studies (National Archives of India)',
    'Jawaharlal Nehru University (JNU)',
    'National Institute of Educational Planning and Administration (NIEPA)',
    'National University of Educational Planning and Administration (NUEPA)',
    'Rashtriya Ayurveda Vidyapeeth (RAV Delhi)',
    'South Asian University (SAU)',
    'University of Delhi (Delhi University)',
    'Ambedkar University Delhi',
    'Delhi Pharmaceutical Sciences and Research University (DPSRU)',
    'Delhi Skill and Entrepreneurship University (DSEU)',
    'Delhi Technological University (DTU)',
    'Guru Gobind Singh Indraprastha University (GGSIPU)',
    'Indira Gandhi Delhi Technical University For Women (IGDTUW)',
    'National Law University Delhi (NLU Delhi)',
    'Netaji Subhas University of Technology (NSIT)',
    'Central Sanskrit University',
    'Jamia Hamdard',
    'Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha (SLBSRSV)',
    'TERI University',
    'International Management Institute Delhi (IMI Delhi)',
    'All India Institute of Medical Sciences Delhi (AIIMS Delhi)',
    'Delhi School of Communication (DSC)',
    'Indian Agricultural Research Institute (IARI)',
    'Indian Institute of Foreign Trade (IIFT)',
    'Indian Institute of Mass Communication (IIMC)',
    'Indian Institute of Packaging (IIP)',
    'Indian Institute of Technology Delhi (IIT Delhi)',
    'Indian Law Institute (ILI)',
    'Indian Statistical Institute Delhi (ISI Delhi)',
    'Indraprastha Institute of Information Technology Delhi (IIIT Delhi)',
    'Institute of Genomics and Integrative Biology (IGIB)',
    'Institute of Hotel Management Catering and Nutrition Pusa Delhi (IHM Pusa)',
    'Institute of Liver and Biliary Sciences (ILBS)',
    'Institute of Rail Transport (IRT)',
    'LNJN National Institute of Criminology and Forensic Science (NICFS)',
    'Lok Nayak Jayaprakash Narayan National Institute of Criminology and Forensic Science',
    'Morarji Desai National Institute of Yoga (MDNIY)',
    'National Institute of Health and Family Welfare (NIHFW)',
    'National Institute of Immunology (NII)',
    'National Institute of Plant Genome Research (NIPGR)',
    'National Institute of Technology Delhi (NIT Delhi)',
    'National Museum Institute of the History of Art Conservation and Museology (NMIHACM)',
    'National School of Drama (NSD)',
    'Pt Deendayal Upadhyaya National Institute For Persons with Physical Disabilities (IPH New Delhi)',
    'School of Planning and Architecture (SPA Delhi)',
    'All India Institute of Ayurveda (AIIA)',
    'Govind Ballabh Pant Institute of Postgraduate Medical Education and Research (GIPMER)',
    'National Institute of Malaria Research (NIMR)',
    'Goa University',
    'Gujarat Vidyapith',
    'CEPT University',
    'Gujarat Maritime University (GMU)',
    'Indian Institute of Technology Goa (IIT Goa)',
    'Indian Institute of Tourism and Travel Management Goa (IITTM Goa)',
    'Institute for Plasma Research (IPR Gandhinagar)',
    'National Institute of Technology Goa (NIT Goa)',
    'Central University of Gujarat (CUG)',
    'Anand Agricultural University (AAU)',
    'Bhakta Kavi Narsinh Mehta University (BNKMU)',
    'Birsa Munda Tribal University (BMTU)',
    'Children University Gujarat',
    'Dharmsinh Desai University (DDU)',
    'Dr Babasaheb Ambedkar Open University (BAOU)',
    'Gujarat Ayurved University (GAU)',
    'Gujarat National Law University (GNLU)',
    'Gujarat Technological University (GTU)',
    'Gujarat University',
    'Gujarat University of Transplantation Sciences (GUTS)',
    'Hemchandracharya North Gujarat University (NGU)',
    'Indian Institute of Teacher Education (IITE Gandhinagar)',
    'Institute of Infrastructure Technology Research and Management (IITRAM)',
    'Junagadh Agricultural University (JAU)',
    'Kamdhenu University (KU Gandhinagar)',
    'Krantiguru Shyamji Krishna Verma Kachchh University (KSKVKU)',
    'Maharaja Krishnakumarsinhji Bhavnagar University (MKBU)',
    'Maharaja Sayajirao University Baroda (MSU Baroda)',
    'National Forensic Sciences University (NFSU)',
    'Navsari Agricultural University (NAU)',
    'Pandit Deendayal Petroleum University (PDPU)',
    'Rashtriya Raksha University (RRU)',
    'Sardar Patel University Vallabh Vidyanagar (SPUVVN)',
    'Sardarkrushinagar Dantiwada Agricultural University (SDAU)',
    'Saurashtra University',
    'Shree Somnath Sanskrit University (SSSU)',
    'Shri Govind Guru University (SGGU)',
    'State University of Performing and Visual Arts (SUPVA)',
    'Swarnim Gujarat Sports University (SGSU)',
    'Veer Narmad South Gujarat University (VNSGU)',
    'Gati Shakti Vishwavidyalaya (GSV)',
    'Charotar University of Science and Technology (CHARUSAT)',
    'Ahmedabad University',
    'AURO University',
    'Calorx Teachers University',
    'Dharamsinh Desai University (DDIT)',
    'Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT)',
    'Ganpat University',
    'Indrashil University',
    'Indus University',
    'ITM Vocational University',
    'Kadi Sarva Vishwavidyalaya',
    'Karnavati University',
    'Marwadi University',
    'Nirma University',
    'P P Savani University',
    'Parul University',
    'Plastindia International University',
    'RK University',
    'Sage University',
    'Swarnim Startup and Innovation University',
    'Uka Tarsadia University',
    'Indian Institute of Information Technology Surat (IIIT Surat)',
    'Indian Institute of Information Technology Vadodara (IIIT Vadodara)',
    'Indian Institute of Management Ahmedabad (IIM Ahmedabad)',
    'Indian Institute of Technology Gandhinagar (IIT Gandhinagar)',
    'National Institute of Pharmaceutical Education and Research Ahmedabad (NIPER Ahmedabad)',
    'Sardar Vallabhbhai National Institute of Technology Surat (SVNIT Surat)',
    'Central University of Haryana (CUH)',
    'Bhagat Phool Singh Women University Sonepat (BPS Women University)',
    'Chaudhary Bansi Lal University (CBLU)',
    'Chaudhary Charan Singh Haryana Agricultural University (CCS HAU)',
    'Chaudhary Devi Lal University (CDLU)',
    'Chaudhary Ranbir Singh University (CRSU)',
    'Deenbandhu Chhotu Ram University of Science and Technology (DCRUSTM)',
    'Guru Jambheshwar University of Science and Technology (GJUST)',
    'Gurugram University',
    'Haryana Institute of Civil Aviation (HICA)',
    'Indira Gandhi University Meerpur (IGU Meerpur)',
    'JC Bose University of Science and Technology (YMCA)',
    'Kurukshetra University',
    'Lala Lajpat Rai University of Veterinary and Animal Sciences (LUVAS)',
    'Maharana Pratap Horticultural University (MHU)',
    'Maharshi Dayanand University Rohtak (MDU Rohtak)',
    'Pandit Bhagwat Dayal Sharma University of Health Sciences Rohtak (UHSR Rohtak)',
    'Pandit Lakhmi Chand State University of Performing and Visual Arts (PLC Supva)',
    'Sardar Patel University Mandi (SPU Mandi)',
    'Shri Vishwakarma Skill University (SVSU)',
    'Bharati Vidyapeeth',
    'Lingyas University',
    'Maharishi Markandeshwar University Mullana (MMU)',
    'Manav Rachna International University',
    'Al-Falah University',
    'Ansal University',
    'Apeejay Stya University',
    'Ashoka University',
    'Baba Mast Nath University',
    'BML Munjal University',
    'GD Goenka University',
    'Geeta University',
    'IILM University',
    'Jagannath University Bahadurgarh',
    'KR Mangalam University',
    'MVN University',
    'NIILM University',
    'O P Jindal Global University',
    'PDM University',
    'Shree Guru Gobind Singh Tricentenary University',
    'Starex University',
    'The Northcap University',
    'Dr BR Ambedkar National Law University (DBRANLU)',
    'Indian Institute of Information Technology Sonepat (IIIT Sonepat)',
    'Indian Institute of Management Rohtak (IIM Rohtak)',
    'Institute of Microbial Technology (IMTECH Chandigarh)',
    'National Institute of Technology Kurukshetra (NIT Kurukshetra)',
    'Pandit Bhagwat Dayal Sharma Post Graduate Institute of Medical Sciences Rohtak (PGIMS Rohtak)',
    'National Dairy Research Institute (NDRI)',
    'National Institute of Food Technology Entrepreneurship and Management (NIFTEM)',
    'Translational Health Science and Technology Institute (THSTI)',
    'Central University of Himachal Pradesh (CU Himachal Pradesh)',
    'Chaudhary Sarwan Kumar Himachal Pradesh Krishi Vishvavidyalaya (CSKHPKV)',
    'Dr Yashwant Singh Parmar University of Horticulture and Forestry (YSP University)',
    'Himachal Pradesh National Law University Shimla (HPNLU Shimla)',
    'Himachal Pradesh Technical University (HIMTU)',
    'Himachal Pradesh University (HPU)',
    'Alakh Prakash Goyal Shimla University',
    'Arni University',
    'Baddi University of Emerging Sciences and Technologies (BUEST)',
    'Bahra University',
    'Chitkara University',
    'Eternal University',
    'IEC University',
    'Maharaja Agrasen University',
    'Manav Bharti University',
    'Shoolini University',
    'Sri Sai University',
    'Himalayan Forest Research Institute (HFRI)',
    'Indian Institute of Information Technology Una (IIIT Una)',
    'Indian Institute of Management Sirmaur (IIM Sirmaur)',
    'Indian Institute of Technology Mandi (IIT Mandi)',
    'National Institute of Technology Hamirpur (NIT Hamirpur)',
    'Institute of Himalayan Bioresource Technology (IHBT)',
    'Central University of Jammu (CU Jammu)',
    'Central University of Kashmir (CUK)',
    'Shri Mata Vaishno Devi University (SMVDU)',
    'Baba Ghulam Shah Badshah University (BGSBU)',
    'Cluster University of Jammu',
    'Cluster University Srinagar (CU Srinagar)',
    'Islamic University of Science and Technology (IUST)',
    'Shere Kashmir University of Agricultural Sciences and Technology (SKUAST Kashmir)',
    'Shere Kashmir University of Agricultural Sciences and Technology Jammu (SKUAST Jammu)',
    'University of Jammu (Jammu University)',
    'University of Kashmir (Kashmir University)',
    'Netaji Subhas University (NSU)',
    'HEC Training Institute (HTI Ranchi)',
    'Indian Institute of Management Jammu (IIM Jammu)',
    'Indian Institute of Technology Jammu (IIT Jammu)',
    'Jammu Women Govt College (Parade Ground)',
    'National Institute of Technology Srinagar (NIT Srinagar)',
    'Central University of Jharkhand (CUJ)',
    'Binod Bihari Mahto Koyalanchal University (BBMKU)',
    'Birsa Agricultural University Ranchi (BAU Ranchi)',
    'Jharkhand Raksha Shakti University (JRSU)',
    'Kolhan University',
    'National University of Study and Research in Law Ranchi (NUSRL Ranchi)',
    'Nilamber Pitamber University (NPU)',
    'Ranchi University',
    'Sido Kanhu Murmu University (SKMU)',
    'Vinoba Bhave University (VBU)',
    'Ramakrishna Mission Vivekananda Educational and Research Institute (RKMVU)',
    'Birla Institute of Technology Mesra (BIT Mesra)',
    'Arka Jain University',
    'Jharkhand Rai University',
    'Radha Govind University',
    'Sai Nath University',
    'Sarala Birla University (SBU Ranchi)',
    'Usha Martin University',
    'Xavier School of Management (XLRI)',
    'YBN University',
    'Central Institute of Psychiatry Ranchi (CIP Ranchi)',
    'Central Tasar Research and Training Institute (CTRTI)',
    'Indian Institute of Information Technology Ranchi (IIIT Ranchi)',
    'Indian Institute of Management Ranchi (IIM Ranchi)',
    'Indian Institute of Technology Dhanbad (IIT Dhanbad)',
    'National Institute of Advanced Manufacturing Technology (NIAMT)',
    'National Institute of Technology Jamshedpur (NIT Jamshedpur)',
    'SAIL Bokaro School of Nursing',
    'Central University of Karnataka (CUK)',
    'Bangalore University',
    'Davangere University',
    'Dr BR Ambedkar School of Economics University (BASE University)',
    'Gulbarga University (GUG)',
    'Kannada University',
    'Karnataka Folklore University',
    'Karnataka Samskrit University',
    'Karnataka Samskrit University (KSU)',
    'Karnataka State Dr Gangubhai Hangal Music and Performing Arts University',
    'Karnataka State Law University (KSLU)',
    'Karnataka State Open University (KSOU)',
    'Karnataka State Rural Development and Panchayat Raj University (KSRDPRU)',
    'Karnataka State Women University (KSWU)',
    'Karnataka University',
    'Karnataka Veterinary Animal and Fisheries Sciences University (KVAFSU)',
    'Kuvempu University',
    'Mangalore University',
    'National Law School of India University Bengaluru (NLSIU)',
    'Rajiv Gandhi University of Health Sciences (RGUHS)',
    'Rani Channamma University (RCUB)',
    'Tumkur University',
    'University of Agricultural and Horticultural Sciences Shimoga (UHS Shimoga)',
    'University of Agricultural Sciences Bangalore (UAS Bangalore)',
    'University of Agricultural Sciences Dharwad (UAS Dharwad)',
    'University of Agricultural Sciences Raichur (UAS Raichur)',
    'University of Horticultural Sciences Bagalkot (UHS Bagalkot)',
    'University of Mysore (Uni Mysore)',
    'Vijayanagara Sri Krishnadevaraya University (VSKU)',
    'Visvesvaraya Technological University (VTU)',
    'Indian Institute of Science Bangalore (IISC)',
    'BLDE University',
    'Christ University',
    'Jagadguru Sri Shivarathreeswara University (JSS University)',
    'Jain University',
    'KLE University',
    'Manipal University',
    'Narsee Monjee Institute of Management Studies (NMIMS)',
    'Nitte University',
    'Sri Devaraj Urs Academy of Higher Education and Research',
    'Sri Siddhartha Academy of Higher Education',
    'Yenepoya University',
    'Alliance University',
    'Azim Premji University',
    'CMR University',
    'Dayananda Sagar University (DSU)',
    'M S Ramaiah University of Applied Sciences',
    'PES University (PESU)',
    'Presidency University Bangalore',
    'Rai Technology University',
    'REVA University',
    'The University of Trans-Disciplinary Health Sciences and Technology (TDU)',
    'All India Institute of Speech and Hearing (AIISH Mysore)',
    'Army Institute of Fashion and Design (AIFD)',
    'Army Institute of Hotel Management and Catering Technology (AIHMCT)',
    'Central Institute of Indian Languages (CIIL Mysore)',
    'Indian Institute of Information Technology Dharwad (IIIT Dharwad)',
    'Indian Institute of Management Bangalore (IIM Bangalore)',
    'Indian Institute of Plantation Management Bangalore (IIPM Bangalore)',
    'Indian Institute of Technology Dharwad (IIT Dharwad)',
    'Indian Plywood Industries Research and Training Institute (IPIRTI)',
    'Indian Statistical Institute Bangalore (ISI Bangalore)',
    'Institute of Social and Economic Change (ISEC)',
    'International Institute of Information Technology Bangalore (IIIT Bangalore)',
    'International Institute of Information Technology Naya Raipur (IIIT Naya Raipur)',
    'Karnataka Handloom Technology Institute Gadag (KHTI Gadag)',
    'National Institute of Mental Health and Neurosciences (NIMHANS)',
    'National Institute of Technology Surathkal (NIT Surathkal)',
    'Raman Research Institute Bangalore (RRI Bangalore)',
    'Central Food Technological Research Institute (CFTRI)',
    'Indian Institute of Astrophysics (IIAP)',
    'Institute of Wood Science and Technology (IWST)',
    'Central University of Kerala (CU Kerala)',
    'Cochin University of Science and Technology (CUSAT)',
    'Kannur University',
    'Kerala Agricultural University (KAU)',
    'Kerala University',
    'Kerala University of Digital Sciences Innovation and Technology (Digital University Kerala)',
    'Kerala University of Fisheries and Ocean Studies (KUFOS)',
    'Kerala University of Health Sciences (KUHS)',
    'Kerala Veterinary and Animal Sciences University (KVASU)',
    'Mahatma Gandhi University Kerala (MGU Kerala)',
    'National University of Advanced Legal Studies (NUALS)',
    'Sree Sankaracharya University of Sanskrit (SSUS)',
    'Thunchath Ezhuthachan Malayalam University',
    'University of Calicut',
    'Darul Huda Islamic University (DHIU)',
    'Association of the Managements of Christian Self Financing Nursing Colleges of Kerala (AMCSFNCK)',
    'Indian Institute of Handloom Technology Kannur (IIHT Kannur)',
    'Indian Institute of Information Technology Kottayam (IIIT Kottayam)',
    'Indian Institute of Management Kozhikode (IIM Kozhikode)',
    'Indian Institute of Science Education and Research Thiruvananthapuram (IISER Thiruvananthapuram)',
    'Indian Institute of Space Science and Technology (IIST)',
    'Indian Institute of Technology Palakkad (IIT Palakkad)',
    'Kerala State Institute of Design (KSID)',
    'National Institute of Technology Calicut (NIT Calicut)',
    'Sree Chitra Tirunal Institute for Medical Sciences and Technology (SCTIMST)',
    'National Institute of Speech and Hearing (NISH)',
    'District Institute of Education and Training Lakshadweep (DIET Lakshadweep)',
    'Kavaratti Institute of Paramedical Sciences',
    'Dr Hari Singh Gour University (DHSGSU)',
    'Indira Gandhi National Tribal University (IGNTU)',
    'Atal Bihari Vajpayee Hindi Vishwavidyalaya (ABVHV)',
    'Awadhesh Pratap Singh University (APSU)',
    'Barkatullah University',
    'Devi Ahilya University (DAUNIV)',
    'Dr BR Ambedkar University of Social Sciences (BRAUSS)',
    'Jawaharlal Nehru Krishi Vishwavidyalaya (JNKVV)',
    'Jiwaji University',
    'Madhya Pradesh Bhoj Open University (MPBOU)',
    'Madhya Pradesh Medical Science University (MPMSU)',
    'Maharaja Chhatrasal Bundelkhand University Chhatarpur (MCBU Chhatarpur)',
    'Maharishi Mahesh Yogi Vedic University (MMYVU)',
    'Maharishi Panini Sanskrit Evam Vedic Vishwavidyalaya (MPSVV Ujjain)',
    'Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya (MGCGV Chitrakoot)',
    'Makhanlal Chaturvedi Rashtriya Patrakarita Avam Sanchar Vishwavidyalaya (MCU Bhopal)',
    'Nanaji Deshmukh Veterinary Science University (NDVSU)',
    'National Law Institute University (NLIU Bhopal)',
    'North Eastern Indira Gandhi Regional Institute of Health and Medical Sciences (NEIGRIHMS)',
    'Raja Mansingh Tomar Music and Arts University',
    'Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV)',
    'Rajmata Vijayaraje Scindia Krishi Vishwa Vidyalaya (RVSKVV)',
    'Rani Durgavati Vishwavidyalaya (RDV Jabalpur)',
    'Sanchi University of Buddhist Indic Studies (Sanchi University)',
    'Vikram University Ujjain',
    'National Institute of Construction Management and Research (NICMAR)',
    'MGM University of Health Sciences Mumbai (MGMUHS)',
    'AISECT University',
    'AKS University',
    'G H Raisoni University',
    'IES University',
    'ITM University Gwalior',
    'Jagran Lakecity University',
    'Mandsaur University',
    'Mangalayatan University Jabalpur',
    'Oriental University',
    'Peoples University Bhopal',
    'PK University',
    'Rabindranath Tagore University (RNTU Bhopal)',
    'RKDF University',
    'Sarvepalli Radhakrishnan University (SRKU)',
    'Swami Vivekanand University (SVNU Sagar)',
    'Techno Global University',
    'All India Institute of Medical Sciences Bhopal (AIIMS Bhopal)',
    'Atal Bihari Vajpayee Indian Institute of Information Technology and Management Gwalior (IIITM Gwalior)',
    'Footwear Design and Development Institute (FDDI)',
    'Indian Institute of Forest Management (IIFM Bhopal)',
    'Indian Institute of Information Technology Bhopal (IIIT Bhopal)',
    'Indian Institute of Information Technology Design and Manufacturing Jabalpur (IIITDM Jabalpur)',
    'Indian Institute of Management Indore (IIM Indore)',
    'Indian Institute of Science Education and Research Bhopal (IISER Bhopal)',
    'Indian Institute of Technology Indore (IIT Indore)',
    'Indian Institute of Tourism and Travel Management  Bhubaneswar (IITTM Bhubaneswar)',
    'Indian Institute of Tourism and Travel Management Gwalior (IITTM Gwalior)',
    'Institute of Hotel Management Catering Technology and Applied Nutrition Mumbai (IHMCTAN Mumbai)',
    'Institute of Hotel Management Gwalior (IHM Gwalior)',
    'Jabalpur Engineering College (JEC)',
    'Lakshmibai National University of Physical Education (LNIPE)',
    'Maulana Azad National Institute of Technology (MANIT Bhopal)',
    'National Institute of Technical Teachers Training and Research Bhopal (NITTTR Bhopal)',
    'Regional Institute of Education Bhopal (RIE Bhopal)',
    'School of Planning and Architecture Bhopal (SPA Bhopal)',
    'Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya (MGAHV)',
    'Dr Babasaheb Ambedkar Marathwada University (BAMU)',
    'Dr Babasaheb Ambedkar Technological University (DBATU)',
    'Dr Balasaheb Sawant Konkan Krishi Vidyapeeth (DBSKKV)',
    'Dr Homi Bhabha State University',
    'Dr Panjabrao Deshmukh Krishi Vidyapeeth Akola (PDKV)',
    'Gondwana University',
    'HSNC University',
    'Kavayitri Bahinabai Chaudhari North Maharashtra University (NMU)',
    'Kavikulaguru Kalidas Sanskrit University (KKSU)',
    'Maharashtra Animal and Fishery Sciences University (MAFSU)',
    'Maharashtra National Law University Aurangabad (MNLU Aurangabad)',
    'Maharashtra National Law University Mumbai (MNLU Mumbai)',
    'Maharashtra National Law University Nagpur (MNLU Nagpur)',
    'Maharashtra University of Health Sciences (MUHS)',
    'Mahatma Phule Krishi Vidyapeeth (MPKV)',
    'Rashtrasant Tukadoji Maharaj Nagpur University (RTMNU)',
    'Sant Gadge Baba Amravati University (SGBAU)',
    'Savitribai Phule Pune University (SBPPU)',
    'Shivaji University',
    'Shreemati Nathibai Damodar Thackersey Women University (SNDT University)',
    'Solapur University',
    'Swami Ramanand Teerth Marathwada University (SRTMUN)',
    'University of Mumbai (Mumbai University)',
    'Vasantrao Naik Marathwada Krishi Vidyapeeth (VNMKV)',
    'Yashwantrao Chavan Maharashtra Open University (YCMOU)',
    'Defence Institute of Advanced Technology (DIAT Pune)',
    'Homi Bhabha National Institute (HBNI)',
    'Indira Gandhi Institute of Development Research (IGIDR)',
    'Institute of Chemical Technology Mumbai (ICT Mumbai)',
    'International Institute for Population Sciences (IIPS)',
    'Tata Institute of Fundamental Research (TIFR)',
    'Tata Institute of Social Sciences (TISS)',
    'Tilak Maharashtra University (TMU)',
    'Chinmaya Vishwavidyapeeth',
    'Datta Meghe Institute of Medical Sciences (DMIMSU)',
    'Deccan College Post-Graduate and Research Institute',
    'DY Patil University',
    'Gokhale Institute of Politics and Economics (GIPE)',
    'Krishna Institute of Medical Sciences (KIMS)',
    'MGM University of Health Sciences',
    'Pravara Institute of Medical Sciences',
    'Symbiosis International University',
    'Ajeenkya D Y Patil University (ADYPU)',
    'Akhil Bharatiya Gandharva Mahavidyalaya Mandal (ABGMVM)',
    'Apex University',
    'Chhatrapati Shivaji Maharaj University (CSMU)',
    'FLAME University',
    'Indian Institute of Science Education and Research Pune (IISER Pune)',
    'MIT - ADT University',
    'Sandip University',
    'SP Jain Institute of Management and Research (SPJIMR)',
    'Tolani Maritime Institute (TMI Pune)',
    'Academy of Scientific and Innovative Research (AcSIR)',
    'Ali Yavar Jung National Institute of Speech and Hearing Disabilities (AYJNIHH Mumbai)',
    'All India Institute of Physical Medicine and Rehabilitation (AIIPMR)',
    'Indian Institute of Banking and Finance (IIBF)',
    'Indian Institute of Information Technology Nagpur (IIIT Nagpur)',
    'Indian Institute of Information Technology Pune (IIIT Pune)',
    'Indian Institute of Management Mumbai (IIM Mumbai)',
    'Indian Institute of Management Nagpur (IIM Nagpur)',
    'Indian Institute of Technology Bombay (IIT Bombay)',
    'National Academy of Defence Production (NADP Nagpur)',
    'National Fire Service College (NFSC Nagpur)',
    'National Institute For Research in Reproductive Health (NIRRH)',
    'National Institute of Abiotic Stress Management (NIASM)',
    'National Institute of Bank Management (NIBM Pune)',
    'National Institute of Securities Markets (NISM)',
    'National Insurance Academy (NIA Pune)',
    'Vaikunth Mehta National Institute of Cooperative Management (VAMNICOM)',
    'Visvesvaraya National Institute of Technology (VNIT Nagpur)',
    'Central Institute of Fisheries Education (CIFE)',
    'Indian Institute of Geomagnetism (IIGM)',
    'Central Agricultural University (CAU)',
    'Manipur University',
    'National Sports University Manipur (NSU Manipur)',
    'Manipur Technical University',
    'Manipur University Of Culture (MUC)',
    'Sangai International University (SIU Manipur)',
    'Indian Institute of Information Technology Manipur (IIIT Manipur)',
    'National Institute of Technology Manipur (NIT Manipur)',
    'English and Foreign Languages University (EFL)',
    'North Eastern Hill University (NEHU)',
    'CMJ University',
    'Mahatma Gandhi University Meghalaya (MGU Meghalaya)',
    'Martin Luther Christian University (MLCU)',
    'University of Science and Technology (USTM)',
    'University of Technology and Management (UTM)',
    'William Carey University (WCU Shillong)',
    'Indian Institute of Management Shillong (IIM Shillong)',
    'National Institute of Technology Meghalaya (NIT Meghalaya)',
    'National Law University Meghalaya (NLU Meghalaya)',
    'North East Regional Institute of Education (NERIE)',
    'Mizoram University (MZU)',
    'National Institute of Technology Mizoram (NIT Mizoram)',
    'Nagaland University',
    'Global Open University',
    'St Joseph University Nagaland',
    'National Institute of Technology Nagaland (NIT Nagaland)',
    'Indira Gandhi National Open University (IGNOU)',
    'Central University of Orissa (CU Orissa)',
    'All India Institute of Medical Sciences Bhubaneswar (AIIMS Bhubaneswar)',
    'Berhampur University',
    'Biju Patnaik University of Technology (BPUT)',
    'Fakir Mohan University (FMU)',
    'Gangadhar Meher University (GMU Sambalpur)',
    'Khallikote University',
    'Maharaja Sriram Chandra Bhanjadeo University (MSCBU)',
    'National Law University Odisha (NLUO)',
    'Odisha State Open University (OSOU)',
    'Orissa University of Agriculture and Technology (OUAT)',
    'Rama Devi Women University',
    'Ravenshaw University',
    'Sambalpur University',
    'Shri Jagannath Sanskrit Vishvavidyalaya (SJSV)',
    'Utkal University',
    'Utkal University of Culture (UUC)',
    'Veer Surendra Sai University of Technology (VSSUT)',
    'Kalinga Institute of Industrial Technology (KIIT)',
    'Kalinga Institute of Social Sciences (KISS)',
    'ASBM University',
    'Birla Global University (BGU)',
    'Centurion University',
    'International Management Institute Bhubaneswar (IMI Bhubaneswar)',
    'Sri Sri University',
    'Xavier University Bhubaneswar',
    'Indian Institute of Handloom Technology Bargarh (IIHT Bargarh)',
    'Indian Institute of Management Sambalpur (IIM Sambalpur)',
    'Indian Institute of Science Education and Research Berhampur (IISER Berhampur)',
    'Indian Institute of Technology Bhubaneswar (IIT Bhubaneswar)',
    'Institute of Hotel Management Bhubaneswar (IHM Bhubaneswar)',
    'Institute of Life Sciences Bhubaneswar (ILS Bhubaneswar)',
    'Institute of Mathematics and Applications Bhubaneswar (IOMA Bhubaneswar)',
    'International Institute of Information Technology Bhubaneswar (IIIT Bhubaneswar)',
    'National Institute of Science Education and Research (NISER)',
    'National Institute of Technology Rourkela (NIT Rourkela)',
    'Regional Institute of Education Bhubaneswar (RIE Bhubaneswar)',
    'Swami Vivekanand National Institute of Rehabilitation Training and Research (SVNIRTAR Cuttack)',
    'Institute of Physics Bhubaneswar (IOPB)',
    'Pondicherry University',
    'Sri Balaji Vidyapeeth (SBV)',
    'Pondicherry Institute of Medical Sciences (PIMS)',
    'Indira Gandhi Medical College and Research Institute (IGMCRI)',
    'Jawaharlal Institute of Postgraduate Medical Education and Research (JIPMER)',
    'National Institute of Technology Puducherry (NIT Puducherry)',
    'Central University of Punjab (CUP)',
    'Baba Farid University of Health Sciences (BFUHS)',
    'Guru Angad Dev Veterinary and Animal Sciences University (GADVASU)',
    'Guru Nanak Dev University (GNDU)',
    'Guru Ravidas Ayurved University (GRAU Punjab)',
    'I K Gujral Punjab Technical University (IKGPTU)',
    'Jagat Guru Nanak Dev Punjab State Open University (PSOU)',
    'Maharaja Ranjit Singh Punjab Technical University (MRSPTU)',
    'Panjab University',
    'Punjab Agricultural University (PAU)',
    'Punjabi University',
    'Rajiv Gandhi National University of Law (RGNUL)',
    'Sardar Beant Singh State University (SBSSU Gurdaspur)',
    'Sant Longowal Institute of Engineering and Technology (SLIET Longowal)',
    'Thapar Institute of Engineering and Technology',
    'Adesh University',
    'Akal University',
    'CT University',
    'Desh Bhagat University',
    'GNA University',
    'Guru Kashi University',
    'Lovely Professional University (LPU)',
    'Rayat Bahra University',
    'Sant Baba Bhag Singh University',
    'Sri Guru Granth Sahib World University',
    'Army College of Nursing Jalandhar (ACN Jalandhar)',
    'Army Institute of Law (AIL Mohali)',
    'Dr B R Ambedkar National Institute of Technology Jalandhar (NIT Jalandhar)',
    'Indian Institute of Management Amritsar (IIM Amritsar)',
    'Indian Institute of Science Education and Research Mohali (IISER Mohali)',
    'Indian Institute of Technology Ropar (IIT Ropar)',
    'Institute of Hotel Management Gurdaspur (IHM Gurdaspur)',
    'Institute of Nano Science and Technology Mohali (INST Mohali)',
    'National Agri Food Biotechnology Institute (NABI)',
    'National Institute of Pharmaceutical Education and Research (NIPER Mohali)',
    'Netaji Subhas National Institute of Sports (NIS Patiala)',
    'Post Graduate Institute of Medical Education and Research Chandigarh (PGIMER Chandigarh)',
    'Central University of Rajasthan (CURAJ)',
    'Agriculture University Jodhpur',
    'Agriculture University Kota',
    'All India Institute of Medical Sciences Jodhpur (AIIMS Jodhpur)',
    'Dr Sarvepalli Radhakrishnan Rajasthan Ayurved University Jodhpur (RAU Jodhpur)',
    'Govind Guru Tribal University (GGTU)',
    'Haridev Joshi University of Journalism and Mass Communication (HJUJ)',
    'Jagadguru Ramanandacharya Rajasthan Sanskrit University',
    'Jai Narain Vyas University (JNVU)',
    'Maharaja Ganga Singh University (MGSU)',
    'Maharaja Surajmal Brij University (MSBU)',
    'Maharana Pratap University of Agriculture and Technology (MPUAT)',
    'Maharshi Dayanand Saraswati University (MDSU)',
    'Mohanlal Sukhadia University (MLSU)',
    'National Law University Jodhpur (NLU Jodhpur)',
    'Pandit Deendayal Upadhyaya Shekhawati University (PDUSU)',
    'Raj Rishi Bhartrihari Matsya University (RRBMU)',
    'Rajasthan Sports University',
    'Rajasthan Technical University (RTU)',
    'Rajasthan University of Health Sciences (RUHS)',
    'Rajasthan University of Veterinary and Animal Sciences (RAJUVAS)',
    'Sardar Patel University of Police Security and Criminal Justice',
    'Sri Karan Narendra Agriculture University (SKNAU)',
    'Swami Keshwanand Rajasthan Agricultural University (SKRAU)',
    'University of Kota (UOK)',
    'University of Rajasthan (UNIRAJ)',
    'Vardhaman Mahaveer Open University (VMOU)',
    'Banasthali Vidyapith',
    'Birla Institute of Technology and Science Pilani (BITS Pilani)',
    'IIS University Jaipur',
    'Institute of Advanced Studies in Education',
    'Jain Vishva Bharati University (JVBI)',
    'Janardan Rai Nagar Rajasthan Vidyapeeth University',
    'LNM Institute of Information Technology (LNMIIT)',
    'Bhagwant University',
    'Career Point University Kota',
    'Dr KNModi University',
    'Geetanjali University',
    'Jagannath University Jaipur',
    'Jaipur National University',
    'Jayoti Vidyapeeth Womens University',
    'JECRC University',
    'JK Lakshmipat University',
    'Jodhpur National University',
    'Madhav University',
    'Maharishi Arvind University',
    'Mewar University',
    'Mody University',
    'NIIT University',
    'NIMS University',
    'Nirwan University',
    'OPJS University',
    'Pacific University Udaipur',
    'Poornima University',
    'RNB Global University',
    'Sangam University',
    'Shri Jagdishprasad Jhabrmal Tibrewala University',
    'Shridhar University',
    'Singhania University',
    'Sir Padampat Singhania University (SPSU)',
    'Suresh Gyan Vihar University (SGVU)',
    'Vivekananda Global University',
    'Chaudhary Charan Singh National Institute of Agricultural Marketing (CCS NIAM)',
    'Indian Institute of Crafts and Design (IICD Jaipur)',
    'Indian Institute of Handloom Technology Jodhpur (IIHT Jodhpur)',
    'Indian Institute of Information Technology Kota (IIIT Kota)',
    'Indian Institute of Management Udaipur (IIM Udaipur)',
    'Indian Institute of Technology Jodhpur (IIT Jodhpur)',
    'Malaviya National Institute of Technology Jaipur (MNIT Jaipur)',
    'National Institute of Ayurveda Jaipur (NIA Jaipur)',
    'Regional Institute of Education Ajmer (RIE Ajmer)',
    'Central Electronics Engineering Research Institute (CEERI)',
    'Sikkim University',
    'Eastern Institute for Integrated Learning in Management University',
    'Sikkim Manipal University',
    'Sikkim Professional University',
    'National Institute of Technology Sikkim (NIT Sikkim)',
    'National Law University Sikkim (NLU Sikkim)',
    'Central University of Tamil Nadu (CUTN)',
    'National Institute for Empowerment of Persons with Multiple Disablities (NIEPMD)',
    'Alagappa University',
    'Anna University (AU Chennai)',
    'Annamalai University',
    'Bharathiar University',
    'Bharathidasan University (BDU Tiruchirappalli)',
    'Madurai Kamaraj University (MKU)',
    'Manonmaniam Sundaranar University',
    'Mother Teresa Womens University (MTWU)',
    'Periyar University',
    'Tamil Nadu Agricultural University (TNAU)',
    'Tamil Nadu Dr Ambedkar Law University (TNDALU)',
    'Tamil Nadu Dr J Jayalalithaa Fisheries University (TNJFU)',
    'Tamil Nadu Dr MGR Medical University (TNMGRMU)',
    'Tamil Nadu Horticulture University (TNHU)',
    'Tamil Nadu Music and Fine Arts University (TNMAFU)',
    'Tamil Nadu Open University (TNOU)',
    'Tamil Nadu Physical Education and Sports University (TNPESU)',
    'Tamil Nadu Teachers Education University (TNTEU)',
    'Tamil Nadu Veterinary and Animal Sciences University (TANUVAS)',
    'Tamil University',
    'Thiruvalluvar University',
    'University of Madras (UNOM)',
    'Avinashilingam University',
    'Chennai Mathematical Institute (CMI)',
    'Gandhigram Rural Institute (GRI)',
    'AMET University',
    'Bharath University',
    'Chettinad Academy of Research and Education (CARE)',
    'Dr MGR Educational and Research Institute',
    'Hindustan Institute of Technology and Science (HITS)',
    'Karpagam Academy of Higher Education (KAHE)',
    'Karunya University',
    'Noorul Islam University',
    'Periyar Maniammai University',
    'Ponnaiyah Ramajayam Institute of Science and Technology (PRIST University)',
    'SASTRA University',
    'Sathyabama University',
    'Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya',
    'Sri Ramachandra Medical College and Research Institute',
    'St Peter Institute of Higher Education and Research (SPIHER)',
    'Vel Tech Rangarajan Dr Sagunthala RD Institute of Science and Technology (Vel Tech University)',
    'Vellore Institute of Technology (VIT University)',
    'Vels University',
    'Amrita Vishwa Vidyapeetham',
    'Bharat University',
    'BS Abdur Rahman Crescent - Institute of Science',
    'Divine Hands International University (DHIU)',
    'Kalasalingam University',
    'Meenakshi Academy of Higher Education and Research',
    'MGR Educational and Research Institute',
    'Sai University',
    'Saveetha University',
    'Woxsen University',
    'Central Electrochemical Research Institute (CECRI)',
    'Central Institute of Petrochemicals Engineering and Technology (CIPET)',
    'Christian Medical College and Hospital Vellore (CMCH Vellore)',
    'Indian Institute of Handloom Technology Salem (IIHT Salem)',
    'Indian Institute of Information Technology Design and Manufacturing Kancheepuram (IIITDM Kancheepuram)',
    'Indian Institute of Information Technology Tiruchirappalli (IIIT Tiruchirappalli)',
    'Indian Institute of Management Tiruchirappalli (IIM Tiruchirappalli)',
    'Indian Institute of Technology Madras (IIT Madras)',
    'Indian Statistical Institute Chennai (ISI Chennai)',
    'Institute of Mathematical Sciences (IMSC)',
    'Madras Institute of Development Studies (MIDS)',
    'Madras School of Economics (MSE)',
    'National Institute of Technical Teachers Training and Research Chennai (NITTTR Chennai)',
    'National Institute of Technology Tiruchirappalli (NIT Trichy)',
    'National Instructional Media Institute (NIMI)',
    'Rajiv Gandhi National Institute of Youth Development (RGNIYD)',
    'Regional Institute of Education Mysore (RIE Mysore)',
    'Sardar Vallabhbhai Patel International School Of Textiles and Management (SVPISTM)',
    'Tamil Virtual Academy',
    'Central Institute of Brackishwater Aquaculture (CIBA)',
    'Central Leather Research Institute (CLRI)',
    'Indian Institute of Food Processing Technology (IIFPT)',
    'Maulana Azad National Urdu University (MANUU)',
    'University of Hyderabad (UOHYD)',
    'Dr B R Ambedkar Open University (BRAOU)',
    'Kakatiya University',
    'Kaloji Narayana Rao University of Health Sciences (KNRUHS)',
    'Mahatma Gandhi University Nalgonda (MGU Nalgonda)',
    'National Academy of Legal Study and Research University of Law Hyderabad (NALSAR)',
    'Osmania University',
    'Palamuru University',
    'Potti Sreeramulu Telugu University',
    'Professor Jayashankar Telangana State Agricultural University (PJTSAU)',
    'PV Narasimha Rao Telangana Veterinary University (PVNRTVU)',
    'Satavahana University',
    'Sri Konda Laxman Telangana State Horticultural University (SKLTSHU)',
    'Telangana University',
    'Indian Institute of Technology Hyderabad (IIT Hyderabad)',
    'Indian Statistical Institute Hyderabad (ISI Hyderabad)',
    'International Institute of Information Technology Hyderabad (IIIT Hyderabad)',
    'Jawaharlal Nehru Architecture and Fine Arts University (JNAFAU)',
    'National Academy of Construction (NAC)',
    'National Institute for the Empowerment of Persons with Intellectual Disabilities (NIEPID)',
    'National Institute of Animal Biotechnology (NIAB)',
    'National Institute of Pharmaceutical Education and Research Hyderabad (NIPER Hyderabad)',
    'National Institute of Technology Warangal (NIT Warangal)',
    'Nizam Institute of Medical Sciences (NIMS)',
    'Telangana Social Welfare Residential Educational Institutions Society (TSWREIS)',
    'Indian Institute of Chemical Technology (IICT)',
    'Indian Institute of Millets Research (IIMR)',
    'National Academy of Agricultural Research Management (NAARM)',
    'National Geophysical Research Institute (NGRI)',
    'National Institute of Agricultural Extension Management (MANAGE)',
    'National Institute of Nutrition (NIN Hyderabad)',
    'National Institute of Plant Health Management (NIPHM)',
    'National Institute of Rural Development and Panchayati Raj Hyderabad (NIRD)',
    'Telangana Tribal Welfare Residential Educational Institutions Society (TTWREIS)',
    'Tripura University',
    'Agartala Government Medical College',
    'Maharaja Bir Bikram University (MBBU)',
    'National Institute of Technology Agartala (NIT Agartala)',
    'National Law University Tripura (NLU Tripura)',
    'Aligarh Muslim University (AMU)',
    'Babasaheb Bhimrao Ambedkar University (BBAU)',
    'Banaras Hindu University (BHU)',
    'Rajiv Gandhi National Aviation University (RGNAU)',
    'Rani Lakshmi Bai Central Agricultural University (RLBCAU)',
    'University of Allahabad',
    'Acharya Narendra Dev University of Agriculture and Technology (NDUAT)',
    'Atal Bihari Vajpayee Medical University (ABVMU)',
    'Banda University of Agriculture and Technology (BUAT)',
    'Bundelkhand University',
    'Chandra Shekhar Azad University of Agriculture and Technology (CSAUK)',
    'Chaudhary Charan Singh University (CCS University)',
    'Chhatrapati Shahu Ji Maharaj University Kanpur (CSJMU Kanpur)',
    'Deen Dayal Upadhyay Gorakhpur University (DDUGU)',
    'Dr APJ Abdul Kalam Technical University (AKTU)',
    'Dr Bhim Rao Ambedkar University (DBRAU)',
    'Dr Ram Manohar Lohia Avadh University (RMLAU)',
    'Dr Shakuntala Misra National Rehabilitation University (DSMRU)',
    'Gautam Buddha University (GBU)',
    'Harcourt Butler Technical University (HBTU)',
    'Jananayak Chandrashekhar University (JNCU)',
    'Khwaja Moinuddin Chishti Urdu Arabi Farsi University',
    'King Georges Medical University (KGMU)',
    'Maa Shakumbhari University (MSU Saharanpur)',
    'Madan Mohan Malaviya University of Technology (MMMUT)',
    'Maharaja Suhel Dev State University Azamgarh (MSDSU)',
    'Mahatma Gandhi Kashi Vidyapith (MGKVP)',
    'Mahatma Jyotiba Phule Rohilkhand University (MJPRU)',
    'Prof Rajendra Singh University (Rajju Bhaiya University Prayagraj)',
    'Ram Manohar Lohiya National Law University (RMLNLU)',
    'Sampurnanand Sanskrit University (SSVV)',
    'Sardar Vallabhbhai Patel University of Agriculture and Technology (SVBP Meerut)',
    'Siddharth University',
    'University of Lucknow (Lucknow University)',
    'UP Pt Deen Dayal Upadhyay Pashu Chikitsa Vigyan Vishwavidyalaya Evam Go-Ansundhan Sansthan (UPVETUNIV)',
    'Uttar Pradesh Rajarshi Tandon Open University (UPRTOU)',
    'Uttar Pradesh University of Medical Sciences (UPUMS)',
    'Veer Bahadur Singh Purvanchal University (VBSPU)',
    'Central University for Tibetan Studies (CUTS)',
    'Indian Veterinary Research Institute (IVRI)',
    'Sam Higginbottom Institute of Agriculture Technology and Sciences (SHUATS)',
    'Bhatkhande Music Institute',
    'Dayalbagh Educational Institute',
    'Jaypee University of Information Technology',
    'Santosh University',
    'Babu Banarasi Das University',
    'Bennett University',
    'Era University',
    'Galgotias University',
    'GLA University',
    'Glocal University',
    'IFTM University',
    'IIMT University',
    'Institute of Management Technology Ghaziabad (IMT Ghaziabad)',
    'Integral University Lucknow',
    'Invertis University',
    'Jagadguru Rambhadracharya Handicapped University',
    'JS University',
    'Maharishi University',
    'Mangalayatan University Aligarh',
    'Mohammad Ali Jauhar University',
    'Monad University',
    'Nehru Gram Bharti University',
    'Noida International University',
    'Raja Mahendra Pratap Singh State University (RMPSSU Aligarh)',
    'Rama University',
    'Sanskriti University',
    'Sharda University',
    'Shiv Nadar University',
    'Shobhit University',
    'Shri Venkateshwara University',
    'Swami Vivekanand Subharti University',
    'Teerthanker Mahaveer University',
    'Aryabhatta Research Institute of Observational Sciences (ARIES)',
    'Bharatendu Academy of Dramatic Arts',
    'Central Footwear Training Institute (CFTI Agra)',
    'Dr Ram Manohar Lohia Institute of Medical Sciences (DRRMLIMS)',
    'Indian Institute of Handloom Technology Varanasi (IIHT Varanasi)',
    'Indian Institute of Information Technology Allahabad (IIIT Allahabad)',
    'Indian Institute of Information Technology Lucknow (IIIT Lucknow)',
    'Indian Institute of Management Lucknow (IIM Lucknow)',
    'Indian Institute of Remote Sensing (IIRS)',
    'Indian Institute of Technology Kanpur (IIT Kanpur)',
    'Indian Institute of Technology Varanasi (IIT BHU)',
    'Indian Institute of Tourism and Travel Management Noida (IITTM Noida)',
    'Institute of Engineering and Rural Technology Prayagraj (IERT Prayagraj)',
    'Motilal Nehru National Institute of Technology Allahabad (MNNIT Allahabad)',
    'National Institute of Pharmaceutical Education and Research Raebareli (NIPER Raebareli)',
    'National Sugar Institute Kanpur (NSI Kanpur)',
    'NTPC School of Business (NSB)',
    'Rajiv Gandhi Institute of Petroleum Technology (RGIPT)',
    'Sanjay Gandhi Postgraduate Institute of Medical Sciences (SGPGI Lucknow)',
    'Central Drug Research Institute (CDRI)',
    'Hemwati Nandan Bahuguna Garhwal University (HNBGU)',
    'Doon University',
    'Govind Ballabh Pant University of Agriculture and Technology (GBPUAT)',
    'Hemwati Nandan Bahuguna Uttarakhand Medical Education University (HNBUMU)',
    'Kumaun University',
    'Sri Dev Suman Uttarakhand University (SDSUV)',
    'Uttarakhand Aawasiya Vishwavidyalaya',
    'Uttarakhand Ayurveda University (UAU)',
    'Uttarakhand Open University (UOU)',
    'Uttarakhand Sanskrit University (USVV)',
    'Uttarakhand Technical University (UKTECH)',
    'Uttarakhand University of Horticulture and Forestry (UUHF)',
    'Forest Research Institute Dehradun (FRI Dehradun)',
    'Gurukul Kangri Vishwavidyalaya (GKV)',
    'Dev Sanskriti Vishwavidyalaya (DSVV)',
    'DIT University',
    'Graphic Era Hill University (GEHU)',
    'Graphic Era University',
    'Haridwar University',
    'Himalayan Garhwal University',
    'Himgiri Zee University (HZU)',
    'IMS Unison University',
    'Motherhood University',
    'Quantum University',
    'Shri Guru Ram Rai University',
    'Shri Guru Ram Rai University (SGRRU)',
    'Swami Rama Himalayan University (SRHU)',
    'University of Patanjali',
    'University of Petroleum and Energy Studies (UPES)',
    'Uttaranchal University',
    'All India Institute of Medical Sciences Rishikesh (AIIMS Rishikesh)',
    'Indian Institute of Management Kashipur (IIM Kashipur)',
    'Indian Institute of Technology Roorkee (IIT Roorkee)',
    'National Institute of Technology Uttarakhand (NIT Uttarakhand)',
    'Wildlife Institute of India (WII)',
    'Indian Institute of Engineering Science and Technology Shibpur (IIEST Shibpur)',
    'Visva Bharati University (VBU)',
    'Adamas University',
    'Aliah University',
    'Bankura University',
    'Bidhan Chandra Krishi Viswavidyalaya (BCKV)',
    'Calcutta University (CALUNIV)',
    'Cooch Behar Panchanan Barma University (CBPBU)',
    'Diamond Harbour Womens University',
    'Indian Institute of Science Education and Research Kolkata (IISER Kolkata)',
    'Jadavpur University',
    'Kazi Nazrul University (KNU)',
    'Maulana Abul Kalam Azad University of Technology (MAKAUT)',
    'Netaji Subhas Open University (NSOU)',
    'Presidency University',
    'Rabindra Bharati University (RBU)',
    'Raiganj University',
    'Senate of Serampore College (University)',
    'Sidho Kanho Birsha University (SKBU)',
    'The Sanskrit College and University',
    'University of Burdwan',
    'University of Engineering and Management',
    'University of Gour Banga (UGB)',
    'University of Kalyani',
    'University of North Bengal (NBU)',
    'Uttar Banga Krishi Vishwavidyalaya (UBKV)',
    'Vidyasagar University',
    'West Bengal National University of Juridical Sciences (WBNUJS)',
    'West Bengal State University (WBSU)',
    'West Bengal University of Animal and Fishery Sciences (WBUAFS)',
    'West Bengal University of Health Sciences (WBUHS)',
    'West Bengal University of Teachers Training Education Planning and Administration (WBUTTEPA)',
    'Brainware University',
    'JIS University',
    'Seacom Skills University',
    'St Xaviers University',
    'Techno India University',
    'The Neotia University',
    'Bose Institute',
    'Indian Institute of Chemical Biology (IICB)',
    'Indian Institute of Handloom Technology Fulia (IIHT Fulia)',
    'Indian Institute of Information Technology Kalyani (IIIT Kalyani)',
    'Indian Institute of Management Calcutta (IIM Calcutta)',
    'Indian Institute of Social Welfare and Business Management (IISWBM)',
    'Indian Institute of Technology Kharagpur (IIT Kharagpur)',
    'Indian Statistical Institute Kolkata (ISI Kolkata)',
    'International Management Institute Kolkata (IMI Kolkata)',
    'National Institute of Biomedical Genomics (NIBMG)',
    'National Institute of Locomotor Disabilities (NILD)',
    'National Institute of Pharmaceutical Education and Research Kolkata (NIPER Kolkata)',
    'National Institute of Technical Teachers Training and Research Kolkata (NITTTR Kolkata)',
    'National Institute of Technology Durgapur (NIT Durgapur)',
    'SAIL Burnpur School of Nursing',
    'State Medical Faculty of West Bengal (SMFWB)',
    'University of Engineering  Management Kolkata (UEM Kolkata)',
    'Central Sericultural Research and Training Institute (CSRTI)',
  ];
}
